apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: migration
  name: migration
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: migration
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: migration
    spec:
      containers:
        - args:
            - sh
            - -c
            - kafka-topics.sh --create --topic numtest --partitions 1 --bootstrap-server kafka:9092 || kafka-topics.sh --alter --topic numtest --partitions 6 --bootstrap-server kafka:9092
          image: docker.io/bitnami/kafka:latest
          name: migration
          ports:
            - containerPort: 9090
          resources: {}
      restartPolicy: Always
status: {}
