version: '3.8'
services:
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    # volumes:
      # - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=votesdatabase

  metabase:
    image: metabase/metabase:latest
    depends_on:
      - postgres
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
     