apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: metabase
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metabase
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: metabase
    spec:
      containers:
        - image: metabase/metabase:latest
          name: metabase
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
