apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: metabase
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metabase
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: metabase
    spec:
      containers:
        - image: metabase/metabase:latest
          name: metabase
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /dev/random
              name: metabase-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: metabase-claim0
          persistentVolumeClaim:
            claimName: metabase-claim0
            readOnly: true
status: {}
