apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: postgresql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: votesdatabase
            - name: POSTGRES_PASSWORD
              value: pass
            - name: POSTGRES_USER
              value: admin
          name: postgresql
          image: pgsql-init:local
          imagePullPolicy: Never 
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
